"""create initial tables

Revision ID: d7d568f105a9
Revises: 
Create Date: 2026-08-02 17:36:41.852718
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'd7d568f105a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('source', mysql.ENUM('shanghai', 'amap'), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', mysql.ENUM('scheduled', 'manual', 'user_request'), nullable=False),
    sa.Column('request_key', sa.String(length=255), nullable=True),
    sa.Column('started_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('status', mysql.ENUM('running', 'success', 'partial', 'failed'), server_default=sa.text("'running'"), nullable=False),
    sa.Column('received_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('inserted_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('skipped_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_ingestion_runs_source_task_started', 'ingestion_runs', ['source', 'task_type', 'started_at'], unique=False)
    op.create_index('idx_ingestion_runs_started', 'ingestion_runs', ['started_at'], unique=False)
    op.create_index('idx_ingestion_runs_status_started', 'ingestion_runs', ['status', 'started_at'], unique=False)
    op.create_table('lines',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('line_name', sa.String(length=100), nullable=False),
    sa.Column('direction', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('line_type', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('shanghai_line_id', sa.String(length=32), nullable=True),
    sa.Column('amap_line_id', sa.String(length=32), nullable=True),
    sa.Column('first_departure_time', mysql.TIME(), nullable=True),
    sa.Column('last_departure_time', mysql.TIME(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint('direction IN (0, 1)', name='chk_lines_direction'),
    sa.CheckConstraint('line_type IS NULL OR line_type IN (1, 2, 3)', name='chk_lines_type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lines')),
    sa.UniqueConstraint('amap_line_id', name='uq_lines_amap_id'),
    sa.UniqueConstraint('shanghai_line_id', 'direction', name='uq_lines_shanghai_direction'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_lines_name_active', 'lines', ['line_name', 'is_active'], unique=False)
    op.create_table('stops',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('stop_name', sa.String(length=150), nullable=False),
    sa.Column('amap_stop_id', sa.String(length=32), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='chk_stops_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='chk_stops_longitude'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stops')),
    sa.UniqueConstraint('amap_stop_id', name='uq_stops_amap_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_stops_location', 'stops', ['longitude', 'latitude'], unique=False)
    op.create_index('idx_stops_name_active', 'stops', ['stop_name', 'is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('passenger', 'analyst', 'admin'), server_default=sa.text("'passenger'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('arrival_infos',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ingestion_run_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('line_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('stop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('source_up_down', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('collected_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('current_bus_distance_m', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('current_bus_arrival_min', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('current_bus_comfort', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('current_bus_stop_count', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('current_license_plate', sa.String(length=64), nullable=True),
    sa.Column('current_barrier_free', sa.Boolean(), nullable=True),
    sa.Column('next_bus_distance_m', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('next_bus_arrival_min', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('next_bus_stop_count', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('next_license_plate', sa.String(length=64), nullable=True),
    sa.Column('next_barrier_free', sa.Boolean(), nullable=True),
    sa.CheckConstraint('current_bus_comfort IS NULL OR current_bus_comfort IN (0, 1, 2, 3)', name='chk_arrival_comfort'),
    sa.CheckConstraint('source_up_down IS NULL OR source_up_down IN (0, 1)', name='chk_arrival_source_direction'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name='fk_arrival_ingestion_run', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name='fk_arrival_line', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name='fk_arrival_stop', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arrival_infos')),
    sa.UniqueConstraint('ingestion_run_id', 'line_id', 'stop_id', name='uq_arrival_run_line_stop'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_arrival_line_time', 'arrival_infos', ['line_id', 'collected_at'], unique=False)
    op.create_index('idx_arrival_realtime', 'arrival_infos', ['line_id', 'stop_id', 'collected_at'], unique=False)
    op.create_index('idx_arrival_stop_time', 'arrival_infos', ['stop_id', sa.literal_column('collected_at DESC')], unique=False)
    op.create_index('idx_arrival_time', 'arrival_infos', ['collected_at'], unique=False)
    op.create_table('dispatch_schedules',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ingestion_run_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('line_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('collected_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('schedule_code', mysql.SMALLINT(), nullable=True),
    sa.Column('message_default', sa.String(length=255), nullable=True),
    sa.Column('message_short', sa.String(length=255), nullable=True),
    sa.CheckConstraint('schedule_code IS NULL OR schedule_code IN (-1, 0, 1)', name='chk_dispatch_schedule_code'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name='fk_dispatch_schedule_ingestion_run', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name='fk_dispatch_schedule_line', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_schedules')),
    sa.UniqueConstraint('ingestion_run_id', 'line_id', name='uq_dispatch_schedule_run_line'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_dispatch_schedule_line_time', 'dispatch_schedules', ['line_id', 'collected_at'], unique=False)
    op.create_index('idx_dispatch_schedule_time', 'dispatch_schedules', ['collected_at'], unique=False)
    op.create_table('favorite_stops',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('stop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name='fk_favorite_stops_stop', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorite_stops_user', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stop_id', name=op.f('pk_favorite_stops')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_favorite_stops_stop', 'favorite_stops', ['stop_id'], unique=False)
    op.create_table('line_routes',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('line_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('stop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sequence_no', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('shanghai_stop_id', sa.String(length=32), nullable=True),
    sa.CheckConstraint('sequence_no >= 1', name='chk_line_routes_sequence'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name='fk_line_routes_line', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name='fk_line_routes_stop', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_routes')),
    sa.UniqueConstraint('line_id', 'sequence_no', name='uq_line_routes_line_sequence'),
    sa.UniqueConstraint('line_id', 'shanghai_stop_id', name='uq_line_routes_shanghai_stop'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_line_routes_line_stop', 'line_routes', ['line_id', 'stop_id'], unique=False)
    op.create_index('idx_line_routes_stop', 'line_routes', ['stop_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('stop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('queried_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name='fk_query_logs_stop', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_query_logs_user', onupdate='RESTRICT', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_logs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_query_logs_stop_time', 'query_logs', ['stop_id', 'queried_at'], unique=False)
    op.create_index('idx_query_logs_time', 'query_logs', ['queried_at'], unique=False)
    op.create_index('idx_query_logs_user_time', 'query_logs', ['user_id', 'queried_at'], unique=False)
    op.create_table('dispatch_cars',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('schedule_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sequence_no', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('vehicle_text', sa.String(length=64), nullable=True),
    sa.Column('is_barrier_free', sa.Boolean(), nullable=True),
    sa.Column('planned_departure_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('countdown_text', sa.String(length=64), nullable=True),
    sa.Column('countdown_seconds', mysql.INTEGER(unsigned=True), nullable=True),
    sa.CheckConstraint('sequence_no >= 1', name='chk_dispatch_cars_sequence'),
    sa.ForeignKeyConstraint(['schedule_id'], ['dispatch_schedules.id'], name='fk_dispatch_cars_schedule', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_cars')),
    sa.UniqueConstraint('schedule_id', 'sequence_no', name='uq_dispatch_cars_schedule_sequence'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_dispatch_cars_departure', 'dispatch_cars', ['planned_departure_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_table("dispatch_cars")
    op.drop_table("query_logs")
    op.drop_table("line_routes")
    op.drop_table("favorite_stops")
    op.drop_table("dispatch_schedules")
    op.drop_table("arrival_infos")
    op.drop_table("users")
    op.drop_table("stops")
    op.drop_table("lines")
    op.drop_table("ingestion_runs")

